<?php
/**
 * @copyright Copyright (c) 2015 Yiister
 * @license https://github.com/yiister/yii2-gentelella/blob/master/LICENSE
 * @link http://gentelella.yiister.ru
 */

namespace yiister\gentelella\widgets;

use rmrevin\yii\fontawesome\component\Icon;
use yii\base\Exception;
use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

class TopNav extends Widget
{

    public $userThumb = 'http://orig12.deviantart.net/f0ba/f/2012/273/9/4/thumbnail_good_ole_man_leon_mid_life_crisis_by_videavice-d5gceyz.gif';

    public $usernameAttr = 'username';

    public $signinUrl = ['/site/login'];

    /**
     * @var array
     *  The format:
     * [
     *  'label' => 'Some label',
     *  'url' => ['/site/url'],
     *  'badge' => [
     *          'color' => 'red',
     *          'content' => 'string'
     *      ],
     *  'icon' => 'fa-class-icon',
     *  'visible' => 'bool val',
     * ]
     */
    public $profileItems = [];

    public $items = [];
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        \Yii::$app->i18n->translations['gental'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => dirname(__DIR__) . '/messages',
        ];
        if(\Yii::$app->user->isGuest){
            $this->profileItems = [
                [
                    'label' => \Yii::t('gental', 'Log in'),
                    'icon' => 'sign-in',
                    'url' => Url::to($this->signinUrl),
                ]
            ];
        }
        for ($i = 0; $i<count($this->profileItems); $i++){
            $item = $this->profileItems[$i];
            if(!is_array($item))
                throw new Exception('$items should be array of arrays');
            $baseText = $item['label'];
            if(!isset($item['url'])){
                $item['url'] = 'javascript:';
            }
            if(!isset($item['visible'])){
                $this->profileItems[$i]['visible'] = true;
            }
            $this->profileItems[$i]['url'] = Url::to($item['url']);
            if(isset($item['badge']) && is_array($item['badge'])){
                $text = "<span class='badge pull-right bg-{$item['badge']['color']}'>{$item['badge']['content']}</span>";
                $text .= "<span>{$item['label']}</span>";
                $this->profileItems[$i]['label'] = $text;
            }
            if(isset($item['icon'])){
                $this->profileItems[$i]['label'] = '<i class="fa pull-right fa-' . $item['icon'] . '"></i> ' . $baseText;
            }

        }

    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        ob_start();
        ?>
        <div class="top_nav">

            <div class="nav_menu">
                <nav class="" role="navigation">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">

                        <?= $this->userDetails(); ?>

                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                                <span class="badge bg-green">6</span>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <a>
                      <span class="image">
                                        <img src="http://placehold.it/128x128" alt="Profile Image" />
                                    </span>
                                        <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                                        <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                      <span class="image">
                                        <img src="http://placehold.it/128x128" alt="Profile Image" />
                                    </span>
                                        <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                                        <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                      <span class="image">
                                        <img src="http://placehold.it/128x128" alt="Profile Image" />
                                    </span>
                                        <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                                        <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                      <span class="image">
                                        <img src="http://placehold.it/128x128" alt="Profile Image" />
                                    </span>
                                        <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                                        <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                                    </a>
                                </li>
                                <li>
                                    <div class="text-center">
                                        <a href="/">
                                            <strong>See All Alerts</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>

        </div>
        <?php

        return ob_get_clean();
    }

    private function userDetails()
    {
        ob_start();
        ?>
        <li class="">
            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <img src="<?= $this->userThumb ?>" alt=""><?= \Yii::$app->user->identity->{$this->usernameAttr} ?>

                <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
                <?php foreach ($this->profileItems as $item): ?>

                    <li>
                        <?= Html::a($item['label'], $item['url']) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
        <?php
        return ob_get_clean();
    }

    protected function renderItems()
    {

    }

}
